<a href="https://colab.research.google.com/github/yuejia-zeng/.github.io/blob/main/Feedforward_version1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import necessary libraries
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# Set random seed for reproducibility
torch.manual_seed(42)
#Neural networks start with randomly initialized weights and biases.
#The seed ensures that this randomness is repeatable.
#Changing the seed will result in a different set of starting weights and biases for each layer of the model.
#This can lead to different training dynamics and possibly different final performance (e.g., loss and accuracy).
#With torch.manual_seed(42), every run of your script will produce the same results, provided all other factors remain constant.

In [8]:
# Define a simple neural network for predicting exam scores
class ExamScoreNN(nn.Module):
    def __init__(self):
        super(ExamScoreNN, self).__init__()
        # Define a single hidden layer with 5 neurons
        #YOUR CODE GOES HERE
        self.hidden = nn.Linear(2,5)

        # Define the output layer with 1 neuron
        #YOUR CODE GOES HERE
        self.output = nn.Linear(5,1)

    def forward(self, x):
        # Apply ReLU activation to the hidden layer
        x = torch.relu(self.hidden(x))
        # Pass the result through the output layer
        x = self.output(x)
        return x


In [9]:
# Instantiate the neural network
model = ExamScoreNN()

# Print the model architecture
print("Model Architecture:")
print(model)

Model Architecture:
ExamScoreNN(
  (hidden): Linear(in_features=2, out_features=5, bias=True)
  (output): Linear(in_features=5, out_features=1, bias=True)
)


In [10]:
# Define a simple dataset for predicting exam scores
# Features: [Hours Studied, Hours of Sleep Before Exam]
data = torch.tensor([
    [1.0, 5.0],  # Example: 1 hour studied, 5 hours of sleep
    [2.0, 6.0],  # Example: 2 hours studied, 6 hours of sleep
    [3.0, 4.0],  # Example: 3 hours studied, 4 hours of sleep
    [4.0, 7.0]   # Example: 4 hours studied, 7 hours of sleep
])
# Labels: [Exam Scores]
labels = torch.tensor([
    [50.0],  # Predicted exam score for 1 hour studied, 5 hours sleep
    [65.0],  # Predicted exam score for 2 hours studied, 6 hours sleep
    [70.0],  # Predicted exam score for 3 hours studied, 4 hours sleep
    [85.0]   # Predicted exam score for 4 hours studied, 7 hours sleep
])


In [11]:
# Define the loss function (Mean Squared Error)
criterion = nn.MSELoss()

# Define the optimizer (Stochastic Gradient Descent)
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Number of training epochs
epochs = 100

In [12]:
# Training loop
for epoch in range(epochs):
    # Forward pass
    outputs = model(data)
    loss = criterion(outputs, labels)

    # Backpropagation
    optimizer.zero_grad()  # Clear previous gradients
    loss.backward()        # Compute gradients
    optimizer.step()       # Update weights

    # Print loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}")


Epoch [100/100], Loss: 246.6095


In [13]:
# Test the trained model
with torch.no_grad():
    test_outputs = model(data)
    print("\nFinal Predictions:")
    print(test_outputs)
    print("Actual Labels:")
    print(labels)



Final Predictions:
tensor([[58.1844],
        [58.1844],
        [58.1844],
        [58.1844]])
Actual Labels:
tensor([[50.],
        [65.],
        [70.],
        [85.]])


In [14]:
   # Test a specific student who studied for 10 hours and slept for 1 hour
specific_student = torch.tensor([[10.0, 1.0]])
specific_output = model(specific_student)
print("\nPrediction for a student who studied 10 hours and slept 1 hour:")
print(specific_output)


Prediction for a student who studied 10 hours and slept 1 hour:
tensor([[56.9710]], grad_fn=<AddmmBackward0>)
